version: '3.1'
services:
  task-webhook:
    build: .
    entrypoint: ./task-webhook
    volumes:
        - ./config:/opt/go-example-webservices/config
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${TASK_API_PORT}:8080
    restart: always
  auth:
    build: .
    entrypoint: ./auth
    ports:
      - ${AUTH_API_PORT}:8080
    restart: always
