---
dependencies:
  authAPI:
    host: auth
    port: 8080
    tls: false

tasks:
  - name: restart task api
    command: docker compose restart task-webhook
  - name: restart auth api
    command: docker compose restart auth
...
