openapi: 3.0.0
info:
  version: 0.0.1
  title: Task Webhook API
  description: An API providing an interface to execute tasks.
servers:
  - url: http://0.0.0.0:8080
paths:
  /:
    post:
      description: Executes a task
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        "400":
          description: Malformed request
        "403":
          description: Not authenticated
        "404":
          description: Task not found
components:
  schemas:
    TaskResponse:
      type: object
      properties:
        id:
          type: string
          description: The task ID.
